### ISSUE TITLE
Blog Modification

### ISSUE THREAD

**Issue by TechnoAyan** [mozillakolkata/blog#1]
@anistark need to do some modification
1. Need to change the background photo.
2. Remove the About us and Archive button above
3. Create a mozilla icon in the address bar
4. Heading should be "Mozilla Kolkata - Official Blog"

Others are cool

cc - @birajkarmakar @swarnava @mozillakolkata/owners

**Comment by birajkarmakar** [comment]
>1. Need to change the background photo.
Yes!
>2. Remove the About us and Archive button above\
No. just link with about us with main website about us , archive should be there for old post
>3. Create a mozilla icon in the address bar
Yes
>4. Heading should be "Mozilla Kolkata - Official Blog"
Yes

**Comment by anistark** [comment]
@TechnoAyan Provide new images.. Go ahead and take this up and modify the images..

**Comment by anistark** [comment]
@birajkarmakar Agreed with u on linking with main website about us. @TechnoAyan There is no button. It's auto rendered markdown.. U create a page and button is auto created.

**Comment by TechnoAyan** [comment]
Ohhh..Sukanta and @birajkarmakar have all the images..

**Comment by birajkarmakar** [comment]
please use this three group photo 
 https://technoayan.files.wordpress.com/2014/12/10882215_10203303979787523_2025886798243364093_n.jpg
https://palsukanta.files.wordpress.com/2014/09/group-ln.jpg
https://palsukanta.files.wordpress.com/2015/08/11257155_816957015066739_7371682333231483006_n.jpg

That's enough for now. Will upload better photo later.

@anistark please make MD guide for contributor who will send PR for blog post ASAP.

**Comment by TechnoAyan** [comment]
@anistark are u up for this? or I will assign myself?
I can do but It will take time.. :(

**Comment by anistark** [comment]
@TechnoAyan Do it. I wrote contribution guidelines.. Coordinate with @birajkarmakar and upload the pics..

**Comment by birajkarmakar** [comment]
As discussed with you, @dbbhattacharya  you can use those photos from my last comment in this thread.

**Comment by dbbhattacharya** [comment]
@birajkarmakar  actually i was wondering if we can use different kind of photos (like minions) instead group photos.

**Comment by TechnoAyan** [comment]
Why minions? Its a community.. so no need of Minions.. Yes you can use Mozilla related wallpapers though.. @dbbhattacharya

**Comment by anistark** [comment]
@dbbhattacharya  I'll be 
![codercat](https://cloud.githubusercontent.com/assets/5357586/10094579/e9333832-637e-11e5-8020-81f7a85ff71e.jpg)

**Comment by dbbhattacharya** [comment]
@TechnoAyan  it's not a community. It's community blog. Do not get confused between Mozilla Kolkata Community and Mozilla Kolkata Blog. Well thats my suggestion. Now its up to you guys.

@anistark  i love this kind of geeky wallpapers ;)

**Comment by anistark** [comment]
@dbbhattacharya :+1:  but dont steel mine.. :stuck_out_tongue:

**Comment by TechnoAyan** [comment]
@dbbhattacharya I Understand that difference very well.. But its a community blog.. not personal blogs.. Now time for you to realize the difference.. :)

**Comment by TechnoAyan** [comment]
@anistark Are you changing the cover? :package:

**Comment by TechnoAyan** [comment]
@anistark are you changing the blog's cover? :D

**Comment by dbbhattacharya** [comment]
@anistark ok :D 

@TechnoAyan ok..its on process :v

**Comment by anistark** [comment]
@TechnoAyan I'm not doing anything as of now. You guys go ahead, replace the images..
@mozillakolkata/contributors Dont chat here. For that, we got [telegram](https://web.telegram.org/#/im). I'm closing this.
