### ISSUE TITLE
Some things wrong in http://mozillakolkata.github.io/blog/jekyll/2014/07/23/hello-world/

### ISSUE THREAD

**Issue by birajkarmakar** [mozillakolkata/blog#3]
@anistark could  you please take a look here ? I guess here is also some thing wrong at the right hand side after comment section.

**Comment by anistark** [comment]
Yes. Right now, It's linked to my own disqus thread. Gimme access to mozillakolkata mail id. and I'll create a disqus thread for us in there.. And replace this.

**Comment by anistark** [comment]
@TechnoAyan or @swarnava Can you take this up and do it? 
Task: Replace the disqus thread with mozillakolkata disqus thread. Create an account in disqus using mozkol id.

**Comment by birajkarmakar** [comment]
I have sent you mail with credential

**Comment by birajkarmakar** [comment]
@anistark go ahead please and complete this

**Comment by anistark** [comment]
@birajkarmakar Ok.

**Comment by anistark** [comment]
Disqus done.
