### ISSUE TITLE
More here link is not working 

### ISSUE THREAD

**Issue by birajkarmakar** [mozillakolkata/blog#9]
@dbbhattacharya thanks once again for writing this blog. But could you please check there is needed a small correction in the blog. More here link is not working properly. It redirects to the wiki. I guess it's not correct. 

http://mozillakolkata.github.io/blog/jekyll/2015/09/24/have-a-look-over-mozilla-kolkata/

**Comment by swarnava** [comment]
where is it supposed to be redirected to?

**Comment by birajkarmakar** [comment]
Ohh. Sorry ! I apologize for that. I was messed up with other things. 

Closing now.
